<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="guardar_sedes.php">
            *id_usuario<input type="text" name="id_usuario"><br><br>
        *id_ubicacion<input type="text" name="id_ubicacion"><br><br>
        *id_estado<input type="text" name="id_estado"><br><br>
        *fecha<input type="text" name="fecha"><br><br>
        <input type="submit" value="Guardar"><br><br>
    </form>
</body>
</html>