<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="../controlador/ejecucion12.php" method="POST">
        *id del usuario <input type="text" name="id_usuario"><br><br>
        *id de la ubicacion <input type="text" name="id_ubicacion"><br><br>
        *id del estado <input type="text" name="id_estado"><br><br>
        <input name="enviar9" type="submit" value="Guardar"><br><br>
    </form>

    <?php
    require_once($contenido12);
    ?>
</body>
</html>