<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="../controlador/ejecucion5.php" method="POST">
        *nombre del tipo de documento <input type="text" name="nombre_tipo_documento"><br><br>
        <input name="Enviar2" type="submit" value="Guardar"><br><br>
    </form>

    <?php
    require_once($contenido5);
    ?>
</body>
</html>