<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="../controlador/ejecucion2.php" method="POST">
        *nombre de la ubicacion <input type="text" name="nombre_ubicacion"><br><br>
        *descripcion <input type="text" name="descripcion"><br><br>
        *id_sede <input type="text" name="id_sede"><br><br>
        <input name="guardar" type="submit" value="Guardar"><br><br>
    </form>

    <?php
    require_once($contenido2);
    ?>
</body>
</html>