<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="../controlador/ejecucion11.php" method="POST">
        *id del cliente <input type="text" name="id_cliente"><br><br>
        *novedad <input type="text" name="novedad"><br><br>
        <input name="enviar8" type="submit" value="Guardar"><br><br>
    </form>

    <?php
    require_once($contenido11);
    ?>
</body>
</html>