<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="../controlador/ejecucion3.php" method="POST">
        *nombre del nivel <input type="text" name="nombre_nivel"><br><br>
        <input name="Enviar" type="submit" value="Guardar"><br><br>
    </form>

    <?php
    require_once($contenido3);
    ?>
</body>
</html>