<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="../controlador/ejecucion6.php" method="POST">
        *nombre del rol <input type="text" name="nombre_rol"><br><br>
        <input name="Enviar3" type="submit" value="Guardar"><br><br>
    </form>

    <?php
    require_once($contenido6);
    ?>
</body>
</html>