<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="../controlador/ejecucion.php" method="POST">
        *nombre de la sedes <input type="text" name="nombre_sedes"><br><br>
        *direccion <input type="text" name="direccion"><br><br>
        *telefono <input type="text" name="telefono"><br><br>
        <input name="Guardar" type="submit" value="Guardar"><br><br>
    </form>

    <?php
    require_once($contenido);
    ?>
</body>
</html>